builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm

release:
  github:
    owner: tailwarden
    name: komiser
  disable: true

brews:
  - tap:
      owner: tailwarden
      name: homebrew-komiser
    homepage: "https://komiser.io"
    description: "Open-source cloud resource manager."
    license: "ELv2"