builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    skip: true

brews:
  - tap:
      owner: tailwarden
      name: homebrew-komiser
    url_template: "https://cli.komiser.io/{{ .Tag }}/{{ .Os }}/{{ .Arch }}/komiser"
    homepage: "https://komiser.io"
    description: "Open-source cloud resource manager."
    license: "ELv2"