builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/tailwarden/komiser/internal.Version={{.Version}}
      - -s -w -X github.com/tailwarden/komiser/internal.Buildtime={{.CommitTimestamp}}
      - -s -w -X github.com/tailwarden/komiser/internal.Commit={{.ShortCommit}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

brews:
  - tap:
      owner: tailwarden
      name: homebrew-komiser
    url_template: "https://cli.komiser.io/{{ .Tag }}/{{ .Os }}/{{ .Arch }}/komiser"
    homepage: "https://komiser.io"
    description: "Open-source cloud resource manager."
    license: "ELv2"